# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tabhklsolver.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets

class Ui_tabhklsolver(object):
    def setupUi(self, tabhklsolver):
        tabhklsolver.setObjectName("tabhklsolver")
        tabhklsolver.resize(845, 475)
        self.horizontalLayout = QtWidgets.QHBoxLayout(tabhklsolver)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.vL_solve_1 = QtWidgets.QVBoxLayout()
        self.vL_solve_1.setObjectName("vL_solve_1")
        self.l_solve_hkl = QtWidgets.QLabel(tabhklsolver)
        self.l_solve_hkl.setObjectName("l_solve_hkl")
        self.vL_solve_1.addWidget(self.l_solve_hkl)
        self.lV_solve_hkl = QtWidgets.QListView(tabhklsolver)
        self.lV_solve_hkl.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.lV_solve_hkl.setObjectName("lV_solve_hkl")
        self.vL_solve_1.addWidget(self.lV_solve_hkl)
        self.hL_solve_pB1 = QtWidgets.QHBoxLayout()
        self.hL_solve_pB1.setObjectName("hL_solve_pB1")
        self.pB_solve_choose_hkl = QtWidgets.QPushButton(tabhklsolver)
        self.pB_solve_choose_hkl.setObjectName("pB_solve_choose_hkl")
        self.hL_solve_pB1.addWidget(self.pB_solve_choose_hkl)
        self.l_solve_hkl_count = QtWidgets.QLabel(tabhklsolver)
        self.l_solve_hkl_count.setObjectName("l_solve_hkl_count")
        self.hL_solve_pB1.addWidget(self.l_solve_hkl_count)
        self.vL_solve_1.addLayout(self.hL_solve_pB1)
        self.horizontalLayout.addLayout(self.vL_solve_1)
        self.line = QtWidgets.QFrame(tabhklsolver)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.vL_solve_2 = QtWidgets.QVBoxLayout()
        self.vL_solve_2.setContentsMargins(-1, 25, -1, -1)
        self.vL_solve_2.setObjectName("vL_solve_2")
        self.hL_solve_ins = QtWidgets.QHBoxLayout()
        self.hL_solve_ins.setObjectName("hL_solve_ins")
        self.pB_solve_ins = QtWidgets.QPushButton(tabhklsolver)
        self.pB_solve_ins.setObjectName("pB_solve_ins")
        self.hL_solve_ins.addWidget(self.pB_solve_ins)
        self.l_solve_ins = QtWidgets.QLabel(tabhklsolver)
        self.l_solve_ins.setObjectName("l_solve_ins")
        self.hL_solve_ins.addWidget(self.l_solve_ins, 0, QtCore.Qt.AlignVCenter)
        self.vL_solve_2.addLayout(self.hL_solve_ins)
        self.lE_solve_xtparam = QtWidgets.QLineEdit(tabhklsolver)
        self.lE_solve_xtparam.setObjectName("lE_solve_xtparam")
        self.vL_solve_2.addWidget(self.lE_solve_xtparam)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vL_solve_2.addItem(spacerItem)
        self.hL_solve = QtWidgets.QHBoxLayout()
        self.hL_solve.setObjectName("hL_solve")
        self.pB_solve = QtWidgets.QPushButton(tabhklsolver)
        self.pB_solve.setObjectName("pB_solve")
        self.hL_solve.addWidget(self.pB_solve)
        self.l_solve = QtWidgets.QLabel(tabhklsolver)
        self.l_solve.setObjectName("l_solve")
        self.hL_solve.addWidget(self.l_solve, 0, QtCore.Qt.AlignVCenter)
        self.vL_solve_2.addLayout(self.hL_solve)
        self.bar_solve = QtWidgets.QProgressBar(tabhklsolver)
        self.bar_solve.setProperty("value", 0)
        self.bar_solve.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.bar_solve.setObjectName("bar_solve")
        self.vL_solve_2.addWidget(self.bar_solve)
        self.horizontalLayout.addLayout(self.vL_solve_2)
        self.line_2 = QtWidgets.QFrame(tabhklsolver)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.vL_solve_3 = QtWidgets.QVBoxLayout()
        self.vL_solve_3.setObjectName("vL_solve_3")
        self.l_solve_res = QtWidgets.QLabel(tabhklsolver)
        self.l_solve_res.setObjectName("l_solve_res")
        self.vL_solve_3.addWidget(self.l_solve_res)
        self.lV_solve_res = QtWidgets.QListView(tabhklsolver)
        self.lV_solve_res.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.lV_solve_res.setObjectName("lV_solve_res")
        self.vL_solve_3.addWidget(self.lV_solve_res)
        self.hL_solve_pB2 = QtWidgets.QHBoxLayout()
        self.hL_solve_pB2.setObjectName("hL_solve_pB2")
        self.pB_solve_send = QtWidgets.QPushButton(tabhklsolver)
        self.pB_solve_send.setObjectName("pB_solve_send")
        self.hL_solve_pB2.addWidget(self.pB_solve_send)
        self.l_solve_res_count = QtWidgets.QLabel(tabhklsolver)
        self.l_solve_res_count.setObjectName("l_solve_res_count")
        self.hL_solve_pB2.addWidget(self.l_solve_res_count)
        self.vL_solve_3.addLayout(self.hL_solve_pB2)
        self.horizontalLayout.addLayout(self.vL_solve_3)

        self.retranslateUi(tabhklsolver)
        QtCore.QMetaObject.connectSlotsByName(tabhklsolver)

    def retranslateUi(self, tabhklsolver):
        _translate = QtCore.QCoreApplication.translate
        tabhklsolver.setWindowTitle(_translate("tabhklsolver", "Form"))
        self.l_solve_hkl.setText(_translate("tabhklsolver", "HKL文件"))
        self.pB_solve_choose_hkl.setText(_translate("tabhklsolver", "选择HKL文件"))
        self.l_solve_hkl_count.setText(_translate("tabhklsolver", "已选0个"))
        self.pB_solve_ins.setText(_translate("tabhklsolver", "选择INS文件"))
        self.l_solve_ins.setText(_translate("tabhklsolver", "未选择INS文件"))
        self.lE_solve_xtparam.setPlaceholderText(_translate("tabhklsolver", "此处输入shelxt运行时参数"))
        self.pB_solve.setText(_translate("tabhklsolver", "开始求解"))
        self.l_solve.setText(_translate("tabhklsolver", "未开始求解"))
        self.l_solve_res.setText(_translate("tabhklsolver", "RES文件"))
        self.pB_solve_send.setText(_translate("tabhklsolver", "发送到匹配器"))
        self.l_solve_res_count.setText(_translate("tabhklsolver", "总计0个"))
