# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tabhkleditor.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets

class Ui_tabhkleditor(object):
    def setupUi(self, tabhkleditor):
        tabhkleditor.setObjectName("tabhkleditor")
        tabhkleditor.resize(922, 585)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(tabhkleditor)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.vL_editor_1 = QtWidgets.QVBoxLayout()
        self.vL_editor_1.setObjectName("vL_editor_1")
        self.l_editor_origin = QtWidgets.QLabel(tabhkleditor)
        self.l_editor_origin.setObjectName("l_editor_origin")
        self.vL_editor_1.addWidget(self.l_editor_origin)
        self.lV_editor_origin = QtWidgets.QListView(tabhkleditor)
        self.lV_editor_origin.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.lV_editor_origin.setObjectName("lV_editor_origin")
        self.vL_editor_1.addWidget(self.lV_editor_origin)
        self.hL_editor_pB1 = QtWidgets.QHBoxLayout()
        self.hL_editor_pB1.setObjectName("hL_editor_pB1")
        self.pB_editor_choose = QtWidgets.QPushButton(tabhkleditor)
        self.pB_editor_choose.setObjectName("pB_editor_choose")
        self.hL_editor_pB1.addWidget(self.pB_editor_choose)
        self.pB_editor_delect_origin = QtWidgets.QPushButton(tabhkleditor)
        self.pB_editor_delect_origin.setObjectName("pB_editor_delect_origin")
        self.hL_editor_pB1.addWidget(self.pB_editor_delect_origin)
        self.vL_editor_1.addLayout(self.hL_editor_pB1)
        self.horizontalLayout_2.addLayout(self.vL_editor_1)
        self.vL_editor_2 = QtWidgets.QVBoxLayout()
        self.vL_editor_2.setContentsMargins(-1, 25, -1, -1)
        self.vL_editor_2.setSpacing(9)
        self.vL_editor_2.setObjectName("vL_editor_2")
        self.cB_editor_method = QtWidgets.QComboBox(tabhkleditor)
        self.cB_editor_method.setObjectName("cB_editor_method")
        self.cB_editor_method.addItem("")
        self.cB_editor_method.addItem("")
        self.cB_editor_method.addItem("")
        self.cB_editor_method.addItem("")
        self.cB_editor_method.addItem("")
        self.cB_editor_method.addItem("")
        self.vL_editor_2.addWidget(self.cB_editor_method)
        self.lE_editor_method = QtWidgets.QLineEdit(tabhkleditor)
        self.lE_editor_method.setStatusTip("")
        self.lE_editor_method.setObjectName("lE_editor_method")
        self.vL_editor_2.addWidget(self.lE_editor_method)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vL_editor_2.addItem(spacerItem)
        self.hL_editor_start = QtWidgets.QHBoxLayout()
        self.hL_editor_start.setObjectName("hL_editor_start")
        self.pB_editor_start = QtWidgets.QPushButton(tabhkleditor)
        self.pB_editor_start.setObjectName("pB_editor_start")
        self.hL_editor_start.addWidget(self.pB_editor_start)
        self.l_editor_start = QtWidgets.QLabel(tabhkleditor)
        self.l_editor_start.setText("")
        self.l_editor_start.setTextFormat(QtCore.Qt.AutoText)
        self.l_editor_start.setScaledContents(False)
        self.l_editor_start.setWordWrap(False)
        self.l_editor_start.setIndent(-1)
        self.l_editor_start.setObjectName("l_editor_start")
        self.hL_editor_start.addWidget(self.l_editor_start, 0, QtCore.Qt.AlignVCenter)
        self.vL_editor_2.addLayout(self.hL_editor_start)
        self.bar_editor = QtWidgets.QProgressBar(tabhkleditor)
        self.bar_editor.setProperty("value", 0)
        self.bar_editor.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.bar_editor.setObjectName("bar_editor")
        self.vL_editor_2.addWidget(self.bar_editor)
        self.horizontalLayout_2.addLayout(self.vL_editor_2)
        self.vL_editor_3 = QtWidgets.QVBoxLayout()
        self.vL_editor_3.setObjectName("vL_editor_3")
        self.l_editor_modified = QtWidgets.QLabel(tabhkleditor)
        self.l_editor_modified.setObjectName("l_editor_modified")
        self.vL_editor_3.addWidget(self.l_editor_modified)
        self.lV_editor_modified = QtWidgets.QListView(tabhkleditor)
        self.lV_editor_modified.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.lV_editor_modified.setObjectName("lV_editor_modified")
        self.vL_editor_3.addWidget(self.lV_editor_modified)
        self.hL_editor_pB2 = QtWidgets.QHBoxLayout()
        self.hL_editor_pB2.setObjectName("hL_editor_pB2")
        self.pB_editor_reselect = QtWidgets.QPushButton(tabhkleditor)
        self.pB_editor_reselect.setObjectName("pB_editor_reselect")
        self.hL_editor_pB2.addWidget(self.pB_editor_reselect)
        self.pB_editor_send = QtWidgets.QPushButton(tabhkleditor)
        self.pB_editor_send.setObjectName("pB_editor_send")
        self.hL_editor_pB2.addWidget(self.pB_editor_send)
        self.cB_editor_autosend = QtWidgets.QCheckBox(tabhkleditor)
        self.cB_editor_autosend.setObjectName("cB_editor_autosend")
        self.hL_editor_pB2.addWidget(self.cB_editor_autosend)
        self.vL_editor_3.addLayout(self.hL_editor_pB2)
        self.horizontalLayout_2.addLayout(self.vL_editor_3)

        self.retranslateUi(tabhkleditor)
        self.cB_editor_method.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(tabhkleditor)

    def retranslateUi(self, tabhkleditor):
        _translate = QtCore.QCoreApplication.translate
        tabhkleditor.setWindowTitle(_translate("tabhkleditor", "Form"))
        self.l_editor_origin.setText(_translate("tabhkleditor", "原始HKL文件"))
        self.pB_editor_choose.setText(_translate("tabhkleditor", "选择HKL文件"))
        self.pB_editor_delect_origin.setText(_translate("tabhkleditor", "删除所选"))
        self.cB_editor_method.setCurrentText(_translate("tabhkleditor", "请选择修改方式"))
        self.cB_editor_method.setItemText(0, _translate("tabhkleditor", "请选择修改方式"))
        self.cB_editor_method.setItemText(1, _translate("tabhkleditor", "Exp(F+sigma)"))
        self.cB_editor_method.setItemText(2, _translate("tabhkleditor", "Exp(F)"))
        self.cB_editor_method.setItemText(3, _translate("tabhkleditor", "Exp(sigma)"))
        self.cB_editor_method.setItemText(4, _translate("tabhkleditor", "Scale(F+sigma)"))
        self.cB_editor_method.setItemText(5, _translate("tabhkleditor", "temp"))
        self.lE_editor_method.setPlaceholderText(_translate("tabhkleditor", "此处输入修改参数范围"))
        self.pB_editor_start.setText(_translate("tabhkleditor", "开始自动编辑"))
        self.l_editor_modified.setText(_translate("tabhkleditor", "编辑后HKL文件"))
        self.pB_editor_reselect.setText(_translate("tabhkleditor", "继续编辑所选"))
        self.pB_editor_send.setText(_translate("tabhkleditor", "发送到求解器"))
        self.cB_editor_autosend.setText(_translate("tabhkleditor", "自动"))

