# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tabhklchecker.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets

class Ui_tabhklchecker(object):
    def setupUi(self, tabhklchecker):
        tabhklchecker.setObjectName("tabhklchecker")
        tabhklchecker.resize(922, 585)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(tabhklchecker)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.vL_check_1 = QtWidgets.QVBoxLayout()
        self.vL_check_1.setObjectName("vL_check_1")
        self.l_check_hkl = QtWidgets.QLabel(tabhklchecker)
        self.l_check_hkl.setObjectName("l_check_hkl")
        self.vL_check_1.addWidget(self.l_check_hkl)
        self.tB_check_view = QtWidgets.QTextBrowser(tabhklchecker)
        self.tB_check_view.setObjectName("tB_check_view")
        self.vL_check_1.addWidget(self.tB_check_view)
        self.horizontalLayout_2.addLayout(self.vL_check_1)
        self.line = QtWidgets.QFrame(tabhklchecker)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.vL_check_2 = QtWidgets.QVBoxLayout()
        self.vL_check_2.setContentsMargins(-1, 25, -1, -1)
        self.vL_check_2.setSpacing(9)
        self.vL_check_2.setObjectName("vL_check_2")
        self.vL_check_method = QtWidgets.QVBoxLayout()
        self.vL_check_method.setObjectName("vL_check_method")
        self.rB_check_pattern = QtWidgets.QRadioButton(tabhklchecker)
        self.rB_check_pattern.setChecked(True)
        self.rB_check_pattern.setObjectName("rB_check_pattern")
        self.vL_check_method.addWidget(self.rB_check_pattern)
        self.hL_check_pattern = QtWidgets.QHBoxLayout()
        self.hL_check_pattern.setObjectName("hL_check_pattern")
        self.lE_check_h1 = QtWidgets.QLineEdit(tabhklchecker)
        self.lE_check_h1.setObjectName("lE_check_h1")
        self.hL_check_pattern.addWidget(self.lE_check_h1)
        self.lE_check_k1 = QtWidgets.QLineEdit(tabhklchecker)
        self.lE_check_k1.setObjectName("lE_check_k1")
        self.hL_check_pattern.addWidget(self.lE_check_k1)
        self.lE_check_l1 = QtWidgets.QLineEdit(tabhklchecker)
        self.lE_check_l1.setObjectName("lE_check_l1")
        self.hL_check_pattern.addWidget(self.lE_check_l1)
        self.l_check_pattern = QtWidgets.QLabel(tabhklchecker)
        self.l_check_pattern.setObjectName("l_check_pattern")
        self.hL_check_pattern.addWidget(self.l_check_pattern)
        self.lE_check_h2 = QtWidgets.QLineEdit(tabhklchecker)
        self.lE_check_h2.setObjectName("lE_check_h2")
        self.hL_check_pattern.addWidget(self.lE_check_h2)
        self.lE_check_k2 = QtWidgets.QLineEdit(tabhklchecker)
        self.lE_check_k2.setObjectName("lE_check_k2")
        self.hL_check_pattern.addWidget(self.lE_check_k2)
        self.lE_check_l2 = QtWidgets.QLineEdit(tabhklchecker)
        self.lE_check_l2.setObjectName("lE_check_l2")
        self.hL_check_pattern.addWidget(self.lE_check_l2)
        self.vL_check_method.addLayout(self.hL_check_pattern)
        self.rB_check_seq = QtWidgets.QRadioButton(tabhklchecker)
        self.rB_check_seq.setObjectName("rB_check_seq")
        self.vL_check_method.addWidget(self.rB_check_seq)
        self.hL_check_seq = QtWidgets.QHBoxLayout()
        self.hL_check_seq.setObjectName("hL_check_seq")
        self.l_check_seq = QtWidgets.QLabel(tabhklchecker)
        self.l_check_seq.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.l_check_seq.setObjectName("l_check_seq")
        self.hL_check_seq.addWidget(self.l_check_seq)
        self.lE_check_seqh = QtWidgets.QLineEdit(tabhklchecker)
        self.lE_check_seqh.setObjectName("lE_check_seqh")
        self.hL_check_seq.addWidget(self.lE_check_seqh)
        self.lE_check_seqk = QtWidgets.QLineEdit(tabhklchecker)
        self.lE_check_seqk.setObjectName("lE_check_seqk")
        self.hL_check_seq.addWidget(self.lE_check_seqk)
        self.lE_check_seql = QtWidgets.QLineEdit(tabhklchecker)
        self.lE_check_seql.setObjectName("lE_check_seql")
        self.hL_check_seq.addWidget(self.lE_check_seql)
        self.vL_check_method.addLayout(self.hL_check_seq)
        self.vL_check_2.addLayout(self.vL_check_method)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vL_check_2.addItem(spacerItem)
        self.l_check_status = QtWidgets.QLabel(tabhklchecker)
        self.l_check_status.setText("")
        self.l_check_status.setObjectName("l_check_status")
        self.vL_check_2.addWidget(self.l_check_status)
        self.hL_check_bt = QtWidgets.QHBoxLayout()
        self.hL_check_bt.setObjectName("hL_check_bt")
        self.pB_check_choose = QtWidgets.QPushButton(tabhklchecker)
        self.pB_check_choose.setObjectName("pB_check_choose")
        self.hL_check_bt.addWidget(self.pB_check_choose)
        self.pB_check_start = QtWidgets.QPushButton(tabhklchecker)
        self.pB_check_start.setObjectName("pB_check_start")
        self.hL_check_bt.addWidget(self.pB_check_start)
        self.vL_check_2.addLayout(self.hL_check_bt)
        self.horizontalLayout_2.addLayout(self.vL_check_2)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(2, 1)

        self.retranslateUi(tabhklchecker)
        QtCore.QMetaObject.connectSlotsByName(tabhklchecker)

    def retranslateUi(self, tabhklchecker):
        _translate = QtCore.QCoreApplication.translate
        tabhklchecker.setWindowTitle(_translate("tabhklchecker", "Form"))
        self.l_check_hkl.setText(_translate("tabhklchecker", "HKL文件"))
        self.rB_check_pattern.setText(_translate("tabhklchecker", "模式检查"))
        self.lE_check_h1.setText(_translate("tabhklchecker", "h"))
        self.lE_check_k1.setText(_translate("tabhklchecker", "k"))
        self.lE_check_l1.setText(_translate("tabhklchecker", "l"))
        self.l_check_pattern.setText(_translate("tabhklchecker", "~="))
        self.lE_check_h2.setText(_translate("tabhklchecker", "h"))
        self.lE_check_k2.setText(_translate("tabhklchecker", "k"))
        self.lE_check_l2.setText(_translate("tabhklchecker", "l"))
        self.rB_check_seq.setText(_translate("tabhklchecker", "序列检查"))
        self.l_check_seq.setText(_translate("tabhklchecker", "hkl:"))
        self.lE_check_seqh.setText(_translate("tabhklchecker", "h"))
        self.lE_check_seqk.setText(_translate("tabhklchecker", "0"))
        self.lE_check_seql.setText(_translate("tabhklchecker", "0"))
        self.pB_check_choose.setText(_translate("tabhklchecker", "选择HKL文件"))
        self.pB_check_start.setText(_translate("tabhklchecker", "开始检查"))

