# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tabhklchecker.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_tabhklchecker(object):
    def setupUi(self, tabhklchecker):
        tabhklchecker.setObjectName("tabhklchecker")
        tabhklchecker.resize(1196, 726)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(tabhklchecker)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.vL_check_1 = QtWidgets.QVBoxLayout()
        self.vL_check_1.setContentsMargins(-1, 25, -1, -1)
        self.vL_check_1.setSpacing(9)
        self.vL_check_1.setObjectName("vL_check_1")
        self.pB_check_choose = QtWidgets.QPushButton(tabhklchecker)
        self.pB_check_choose.setObjectName("pB_check_choose")
        self.vL_check_1.addWidget(self.pB_check_choose)
        self.l_check_status = QtWidgets.QLabel(tabhklchecker)
        self.l_check_status.setObjectName("l_check_status")
        self.vL_check_1.addWidget(self.l_check_status)
        self.fL_check = QtWidgets.QFormLayout()
        self.fL_check.setObjectName("fL_check")
        self.l_check_pattern = QtWidgets.QLabel(tabhklchecker)
        self.l_check_pattern.setObjectName("l_check_pattern")
        self.fL_check.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.l_check_pattern)
        self.cB_check_laue = QtWidgets.QComboBox(tabhklchecker)
        self.cB_check_laue.setObjectName("cB_check_laue")
        self.cB_check_laue.addItem("")
        self.cB_check_laue.addItem("")
        self.cB_check_laue.addItem("")
        self.cB_check_laue.addItem("")
        self.cB_check_laue.addItem("")
        self.cB_check_laue.addItem("")
        self.cB_check_laue.addItem("")
        self.cB_check_laue.addItem("")
        self.cB_check_laue.addItem("")
        self.cB_check_laue.addItem("")
        self.cB_check_laue.addItem("")
        self.cB_check_laue.addItem("")
        self.cB_check_laue.addItem("")
        self.cB_check_laue.addItem("")
        self.cB_check_laue.addItem("")
        self.fL_check.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cB_check_laue)
        self.l_check_conf_level = QtWidgets.QLabel(tabhklchecker)
        self.l_check_conf_level.setObjectName("l_check_conf_level")
        self.fL_check.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.l_check_conf_level)
        self.dSB_check_conf_level = QtWidgets.QDoubleSpinBox(tabhklchecker)
        self.dSB_check_conf_level.setMaximum(50.0)
        self.dSB_check_conf_level.setProperty("value", 5.0)
        self.dSB_check_conf_level.setObjectName("dSB_check_conf_level")
        self.fL_check.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.dSB_check_conf_level)
        self.vL_check_1.addLayout(self.fL_check)
        self.hL_check_seq = QtWidgets.QHBoxLayout()
        self.hL_check_seq.setObjectName("hL_check_seq")
        self.rB_check_seq = QtWidgets.QCheckBox(tabhklchecker)
        self.rB_check_seq.setObjectName("rB_check_seq")
        self.hL_check_seq.addWidget(self.rB_check_seq)
        self.l_check_seq = QtWidgets.QLabel(tabhklchecker)
        self.l_check_seq.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.l_check_seq.setObjectName("l_check_seq")
        self.hL_check_seq.addWidget(self.l_check_seq)
        self.cB_check_seqh = QtWidgets.QComboBox(tabhklchecker)
        self.cB_check_seqh.setObjectName("cB_check_seqh")
        self.cB_check_seqh.addItem("")
        self.cB_check_seqh.addItem("")
        self.cB_check_seqh.addItem("")
        self.cB_check_seqh.addItem("")
        self.cB_check_seqh.addItem("")
        self.cB_check_seqh.addItem("")
        self.hL_check_seq.addWidget(self.cB_check_seqh)
        self.cB_check_seqk = QtWidgets.QComboBox(tabhklchecker)
        self.cB_check_seqk.setObjectName("cB_check_seqk")
        self.cB_check_seqk.addItem("")
        self.cB_check_seqk.addItem("")
        self.cB_check_seqk.addItem("")
        self.cB_check_seqk.addItem("")
        self.cB_check_seqk.addItem("")
        self.cB_check_seqk.addItem("")
        self.hL_check_seq.addWidget(self.cB_check_seqk)
        self.cB_check_seql = QtWidgets.QComboBox(tabhklchecker)
        self.cB_check_seql.setObjectName("cB_check_seql")
        self.cB_check_seql.addItem("")
        self.cB_check_seql.addItem("")
        self.cB_check_seql.addItem("")
        self.cB_check_seql.addItem("")
        self.cB_check_seql.addItem("")
        self.cB_check_seql.addItem("")
        self.hL_check_seq.addWidget(self.cB_check_seql)
        self.vL_check_1.addLayout(self.hL_check_seq)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vL_check_1.addItem(spacerItem)
        self.l_check_result = QtWidgets.QLabel(tabhklchecker)
        self.l_check_result.setText("")
        self.l_check_result.setObjectName("l_check_result")
        self.vL_check_1.addWidget(self.l_check_result)
        self.hL_check_bt = QtWidgets.QHBoxLayout()
        self.hL_check_bt.setObjectName("hL_check_bt")
        self.pB_check_start = QtWidgets.QPushButton(tabhklchecker)
        self.pB_check_start.setObjectName("pB_check_start")
        self.hL_check_bt.addWidget(self.pB_check_start)
        self.vL_check_1.addLayout(self.hL_check_bt)
        self.horizontalLayout_2.addLayout(self.vL_check_1)
        self.line = QtWidgets.QFrame(tabhklchecker)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.vL_check_2 = QtWidgets.QVBoxLayout()
        self.vL_check_2.setObjectName("vL_check_2")
        self.l_check_hkl = QtWidgets.QLabel(tabhklchecker)
        self.l_check_hkl.setObjectName("l_check_hkl")
        self.vL_check_2.addWidget(self.l_check_hkl)
        self.tB_check_view = QtWidgets.QTextBrowser(tabhklchecker)
        self.tB_check_view.setObjectName("tB_check_view")
        self.vL_check_2.addWidget(self.tB_check_view)
        self.horizontalLayout_2.addLayout(self.vL_check_2)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(2, 1)

        self.retranslateUi(tabhklchecker)
        QtCore.QMetaObject.connectSlotsByName(tabhklchecker)

    def retranslateUi(self, tabhklchecker):
        _translate = QtCore.QCoreApplication.translate
        tabhklchecker.setWindowTitle(_translate("tabhklchecker", "Form"))
        self.pB_check_choose.setText(_translate("tabhklchecker", "选择HKL文件"))
        self.l_check_status.setText(_translate("tabhklchecker", "未选择文件"))
        self.l_check_pattern.setText(_translate("tabhklchecker", "Laue群"))
        self.cB_check_laue.setItemText(0, _translate("tabhklchecker", "1"))
        self.cB_check_laue.setItemText(1, _translate("tabhklchecker", "-1"))
        self.cB_check_laue.setItemText(2, _translate("tabhklchecker", "2/m"))
        self.cB_check_laue.setItemText(3, _translate("tabhklchecker", "mmm"))
        self.cB_check_laue.setItemText(4, _translate("tabhklchecker", "4/m"))
        self.cB_check_laue.setItemText(5, _translate("tabhklchecker", "4/mmm"))
        self.cB_check_laue.setItemText(6, _translate("tabhklchecker", "-3"))
        self.cB_check_laue.setItemText(7, _translate("tabhklchecker", "-3(R)"))
        self.cB_check_laue.setItemText(8, _translate("tabhklchecker", "-3m1"))
        self.cB_check_laue.setItemText(9, _translate("tabhklchecker", "-31m"))
        self.cB_check_laue.setItemText(10, _translate("tabhklchecker", "-3m(R)"))
        self.cB_check_laue.setItemText(11, _translate("tabhklchecker", "6/m"))
        self.cB_check_laue.setItemText(12, _translate("tabhklchecker", "6/mmm"))
        self.cB_check_laue.setItemText(13, _translate("tabhklchecker", "m-3"))
        self.cB_check_laue.setItemText(14, _translate("tabhklchecker", "m-3m"))
        self.l_check_conf_level.setText(_translate("tabhklchecker", "汇报结果容错阈值"))
        self.rB_check_seq.setText(_translate("tabhklchecker", "序列检查"))
        self.l_check_seq.setText(_translate("tabhklchecker", "hkl:"))
        self.cB_check_seqh.setItemText(0, _translate("tabhklchecker", "0"))
        self.cB_check_seqh.setItemText(1, _translate("tabhklchecker", "1"))
        self.cB_check_seqh.setItemText(2, _translate("tabhklchecker", "2"))
        self.cB_check_seqh.setItemText(3, _translate("tabhklchecker", "3"))
        self.cB_check_seqh.setItemText(4, _translate("tabhklchecker", "n"))
        self.cB_check_seqh.setItemText(5, _translate("tabhklchecker", "-n"))
        self.cB_check_seqk.setItemText(0, _translate("tabhklchecker", "0"))
        self.cB_check_seqk.setItemText(1, _translate("tabhklchecker", "1"))
        self.cB_check_seqk.setItemText(2, _translate("tabhklchecker", "2"))
        self.cB_check_seqk.setItemText(3, _translate("tabhklchecker", "3"))
        self.cB_check_seqk.setItemText(4, _translate("tabhklchecker", "n"))
        self.cB_check_seqk.setItemText(5, _translate("tabhklchecker", "-n"))
        self.cB_check_seql.setItemText(0, _translate("tabhklchecker", "0"))
        self.cB_check_seql.setItemText(1, _translate("tabhklchecker", "1"))
        self.cB_check_seql.setItemText(2, _translate("tabhklchecker", "2"))
        self.cB_check_seql.setItemText(3, _translate("tabhklchecker", "3"))
        self.cB_check_seql.setItemText(4, _translate("tabhklchecker", "n"))
        self.cB_check_seql.setItemText(5, _translate("tabhklchecker", "-n"))
        self.pB_check_start.setText(_translate("tabhklchecker", "开始检查"))
        self.l_check_hkl.setText(_translate("tabhklchecker", "检查结果"))

